version: "2"

services:
  caliper_2.2:
    container_name: caliper_2.2
    image: hyperledger/caliper:0.4.0
    command: launch manager --caliper-fabric-gateway-enabled
    environment:
      - CALIPER_BIND_SUT=fabric:2.1.0
      - CALIPER_BENCHCONFIG=benchmarks/scenario/simple/fabric-v2.2/config.yaml
      - CALIPER_NETWORKCONFIG=networks/fabric/v2.2/network-config.yaml
    volumes:
      - ./caliper-benchmarks-local:/hyperledger/caliper/workspace
    network_mode: host
